#!/bin/sh

while true; do

	echo "1. Install nvm"
	echo "2. Install HOMEBREW and rvm"
	echo "3. Install sdkman"
	echo "4. Install pyenv"
	echo "0. quit"

	read -p "Select: " response </dev/tty
	case $response in
	0)
		exit
	;;
	1)
		echo "installing nvm"
		curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
	;;
	2)
		echo "installing Homebrew"
		yes | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
		echo "installing rvm"
		curl -sSL https://get.rvm.io | bash -s stable --ruby
	;;
	3)
		echo "installing sdkman"
		curl -s "https://get.sdkman.io" | bash
		echo "Now open a new terminal or enter:"
		echo "source \"$HOME/.sdkman/bin/sdkman-init.sh\""
	;;
	4)
		echo "installing pyenv"
		curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
		cat << EOF >> $HOME/.bash_profile
		export PATH="/Users/c.craig/.pyenv/bin:$PATH"
		eval "$(pyenv init -)"
		eval "$(pyenv virtualenv-init -)"
EOF
	;;
	esac
done
